# App: hello → hello.bult.localhost

upstream app_hello {
    server 192.168.252.6:20000;
    keepalive 16;
}

server {
    listen       80;
    server_name  hello.bult.localhost;

    location / {
        proxy_pass  http://app_hello;
    }
}
